
# The directory to the SD card from your Switch (Nintendo folder).  # TODO: Rewords better
SOURCE_FILEPATH: "./Nintendo/Album/"


# This tells the program whether or not to keep the image files on the SD card
# or not. If this is `False`, then you must specify a `TARGET_FILEPATH`, if no
# `TARGET_FILEPATH` is specified, then the software will error.
#
#   VALID OPTIONS:
#       False   - This will cause the software to output the organized images
#                 and videos to the corresponding folder specified in the
#                 `TARGET_FILEPATH` option.
#       True    - This will tell the software to output the images and videos
#                 into the same folder where the Switch stores the Album on the
#                 SD card directly.
KEEP_ON_SD_CARD: False


# This is the filepath of where you want the images and videos to be sent to.
# It is only used if the `KEEP_ON_SD_CARD` option is set to `False`. This can be
# anywhere on your computer.
TARGET_FILEPATH: "Nintendo/Organized/"


FILENAME_FORMAT: "{YYYY}-{MM}-{DD}.{4hh}-{mm}-{ss}"


# Enable updating of all screenshotids via online database.
# This requires a key.txt which contains the AES-ECB key for decrypting ids.
# This can be found in capsrv nso file.
# SHA1 key for the value: 23b1daf105047248f2e51375a17cff6d51e01350
#
# VALID OPTIONS:
#     False   - Allow updating of screenshot ids via online database
#     True    - Disable updating of screen ids via onliny database
UPDATE_TITLE_IDS: True


# If you do not want to manage images or videos, you can modify these values to
# either include (True) or exclude (False) videos or images. One of these
# options MUST be set to True otherwise there is nothing for the program to do.
#
# VALID OPTIONS:
#     False   - Tell the program to ignore files of the specified type
#     True    - Tell the program to include files of the specified type
INCLUDE_IMAGES: True
INCLUDE_VIDEOS: True


#
PROMPT_FOR_UNKNOWN: True