import os
import urllib3
import hashlib
import xmltodict
from Crypto.Cipher import AES
from Crypto.Util import Padding

KEYHASH = "24e0dc62a15c11d38b622162ea2b4383"


def decrypt_title_ID(key, titleid):
    """
    Converts a game titleid to the id screenshots use

    Args:
        key: Decryption key used in conversion
        titleid: titleid to convert

    Returns:
        Converted titleid
    """
    cipher = AES.new(key, AES.MODE_ECB)

    titleidb = bytes.fromhex(titleid)
    titleidb = titleidb[7::-1]
    conversion = titleidb.hex()
    conversion = conversion.ljust(32, '0')
    titleidb = bytes.fromhex(conversion)
    encrypted = cipher.encrypt(titleidb)
    screenshotid = encrypted.hex().upper()

    return screenshotid


def load_key(filename, keyhash):
    """
    Read in key from file

    Args:
         filename: file to open
         keyhash: keyhash of the key (to ensure the key is valid)

    Returns:
        Decryption key

    Raises:
        IOError: When python has issues opening/reading the file
        ValueError: If keyhash doesn't match the hash of the computed key
    """
    with open(filename, 'r') as keyfile:
        keystring = keyfile.read(32)
        key = bytes.fromhex(keystring)

        if(hashlib.md5(key).hexdigest() not in keyhash):
            raise ValueError("Keys don't match!")

        return key


def get_screenshot_ids(key):
    """
        Generates a dictionary where each screenshot id points to the game's name

        Args:
            key: a key generated from load_key()

        Returns:
            Dictionary where each key is a screenshot id and it's corresponding value is the game's name

        Raises:
            ValueError: Unable to parse nswdb's titleid list
    """
    http = urllib3.PoolManager()
    url = "http://nswdb.com/xml.php"
    response = http.request('GET', url)

    try:
        data = xmltodict.parse(response.data)
    except:
        raise ValueError("Unable to parse titleids file")

    screenshotids = {}
    dict_games = data["releases"]["release"]
    for index in range(len(dict_games)):
        curr_game = dict_games[index]

        try:
            dict_key = decrypt_title_ID(key, curr_game["titleid"])
        except ValueError:
            # Can't decrypt key - ignore
            continue

        screenshotids[dict_key] = curr_game["name"]

    return screenshotids


def get_screenshot_dict():
    """
        "Main function" which generates screenshot dict
        Expects key.txt to exist to auto generate screenshotids from titleids

        Returns:
            Dictionary generated by get_screenshot_ids
    """
    try:
        key = load_key("key.txt", KEYHASH)
    except FileNotFoundError:
        print("Decryption key (key.txt) not found!")
    except ValueError:
        print("Decryption key (key.txt) doesn't match!")

    ids = get_screenshot_ids(key)

    return ids


if __name__ == "__main__":
    id_dict = get_screenshot_dict()
    print(id_dict)